<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Electronic Way Bill in GST</title>
    <link rel="stylesheet" href="assets/css/custom.css" />
    <link rel="shortcut icon" href="assets/img/favicon.png" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

</head>

<body>

    <?php include 'header.php' ?>

    <div class="homebanner blogSec">
        <div class="container">

            <div class="onlineTop">
                <h1>Electronic Way Bill in GST</h1>
            </div>

            <div class="boxSec nohover">
                <h4>Introduction</h4>
                <p>A waybill is a receipt or a document issued by a carrier
                    giving details and instructions relating to the shipment
                    of a consignment of goods and the details include name
                    of consignor, consignee, the point of origin of the
                    consignment, its destination, and route.
                    Electronic Way Bill (E-Way Bill) is basically a compliance
                    mechanism wherein by way of a digital interface the person
                    causing the movement of goods uploads the relevant
                    information prior to the commencement of movement of
                    goods and generates e-way bill on the GST portal.</p>
                <p>Rule 138 of the CGST Rules, 2017 provides for the e-way bill
                    mechanism and in this context it is important to note that
                    “information is to be furnished prior to the commencement
                    of movement of goods” and “is to be issued whether the
                    movement is in relation to a supply or for reasons other than
                    supply”.</p>
                <h4>E-Way Bill under GST</h4>
                <p>E-way bill is an electronic document generated on the
                    GST portal evidencing movement of goods. It has two
                    Components-Part A comprising of details of GSTIN of
                    recipient, place of delivery (PIN Code), invoice or challan
                    number and date, value of goods, HSN code, transport
                    document number (Goods Receipt Number or Railway
                    Receipt Number or Airway Bill Number or Bill of Lading
                    Number) and reasons for transportation; and Part B
                    comprising of transporter details (Vehicle number).
                    As per Rule 138 of the CGST Rules, 2017,every registered
                    person who causes movement of goods (which may not
                    necessarily be on account of supply) of consignment
                    value more than Rs. 50000/- is required to furnish above
                    mentioned information in part A of e-way bill. The part B
                    containing transport details helps in generation of e-way
                    bill. </p>
                <h4>Who should generate the e-way bill and why? </h4>
                <p>E-way bill is to be generated by the consignor or consignee
                    himself if the transportation is being done in own/hired
                    conveyance or by railways by air or by Vessel. If the goods
                    are handed over to a transporter for transportation by road,
                    E-way bill is to be generated by the Transporter. Where
                    neither the consignor nor consignee generates the e-way bill
                    and the value of goods is more than Rs.50,000/- it shall be
                    the responsibility of the transporter to generate it.</p>
                <p>Further, it has been provided that where goods are sent by a
                    principal located in one State to a job worker located in any
                    other State, the e-way bill shall be generated by the principal
                    irrespective of the value of the consignment.</p>
            </div>
        </div>
    </div>

    <?php include 'footer.php' ?>

</body>

</html>